#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2019-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script runs on target post installation of nvidia-l4t-kernel-dtbs debian package.

. /usr/share/debconf/confmodule
db_version 2.0


BOOT_CTRL_CONF="/etc/nv_boot_control.conf"

if [ -e "/opt/nvidia/l4t-packages/.nv-l4t-disable-boot-fw-update-in-preinstall" ]; then
        echo "Pre-installing kernel-dtbs package, skip flashing"
        exit 0
fi

function t210ref_boot_dtb()
{
        if [ "${chipid}" != "0x21" ]; then
                return
        fi

        if [ ! -d "/boot/dtb" ]; then
                mkdir -p "/boot/dtb"
        fi

        result=$(find "/boot/dtb" -name "*.dtb")
        if [ -n "${result}" ]; then
                return
        fi

        dtsfilename=$(tr -d '\0' < "/proc/device-tree/nvidia,dtsfilename")
        dtbfilename=$(basename -s .dts "${dtsfilename}")".dtb"
        if [ ! -f "/boot/${dtbfilename}" ]; then
                return
        fi

        cp "/boot/${dtbfilename}" "/boot/dtb/kernel_${dtbfilename}"
        exit 0
}

if [ ! -r "${BOOT_CTRL_CONF}" ]; then
        echo "ERROR. Cannot open ${BOOT_CTRL_CONF} for reading."
        echo "Cannot install package. Exiting..."
        exit 1
fi

chipid=$(awk '/TEGRA_CHIPID/ {print $2}' "${BOOT_CTRL_CONF}")

t210ref_boot_dtb
# shellcheck disable=SC2164
pushd /boot/dtb &> /dev/null
# shellcheck disable=SC2035
DTB=$(ls *.dtb 2> /dev/null)
if [ -n "${DTB}" ]; then
        if [ -f "/boot/${DTB#kernel_}" ]; then
                cp -f "/boot/${DTB#kernel_}" "/boot/dtb/${DTB}"
                if [ "${chipid}" == "0x19" ] && [ -f "/boot/${DTB#kernel_}.sig" ] ; then
                        cp -f "/boot/${DTB#kernel_}.sig" "/boot/dtb/${DTB}.sig"
                fi
        fi
        # shellcheck disable=SC2164
        popd &> /dev/null
fi

exit 0

