# SPDX-License-Identifier: GPL-2.0
#
# Tegra CVNAS Driver.
#
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#

ccflags-y += -I$(srctree.nvidia)/include
ccflags-y += -Werror

obj-$(CONFIG_TEGRA_CVNAS) += cvnas.o
