/*
 * Copyright (c) 2021-2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * This file is autogenerated.  Do not edit.
 */

#ifndef T234_HWPM_REGOPS_ALLOWLIST_H
#define T234_HWPM_REGOPS_ALLOWLIST_H

#include <linux/types.h>
#include <tegra_hwpm.h>

extern struct allowlist t234_perfmon_alist[67];
extern struct allowlist t234_pma_res_cmd_slice_rtr_alist[86];
extern struct allowlist t234_pma_res_pma_alist[1];
extern struct allowlist t234_rtr_alist[8];
extern struct allowlist t234_vi_thi_alist[7];
extern struct allowlist t234_isp_thi_alist[7];
extern struct allowlist t234_vic_alist[9];
extern struct allowlist t234_ofa_alist[8];
extern struct allowlist t234_pva0_pm_alist[9];
extern struct allowlist t234_nvdla_alist[34];
extern struct allowlist t234_mgbe_alist[2];
extern struct allowlist t234_nvdec_alist[8];
extern struct allowlist t234_nvenc_alist[9];
extern struct allowlist t234_pcie_ctl_alist[2];
extern struct allowlist t234_disp_alist[3];
extern struct allowlist t234_mss_channel_alist[2];
extern struct allowlist t234_mss_nvlink_alist[1];
extern struct allowlist t234_mc0to7_res_mss_iso_niso_hub_alist[2];
extern struct allowlist t234_mc8_res_mss_iso_niso_hub_alist[1];
extern struct allowlist t234_mcb_res_mss_iso_niso_hub_alist[3];
extern struct allowlist t234_mcb_mss_mcf_alist[4];
extern struct allowlist t234_mc0to1_mss_mcf_alist[3];
extern struct allowlist t234_mc2to7_mss_mcf_alist[1];

#endif /* T234_HWPM_REGOPS_ALLOWLIST_H */
