/*
 * Copyright (c) 2020-2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This file is autogenerated.  Do not edit.
 */

#include <nvgpu/types.h>
#include <nvgpu/regops_allowlist.h>
#include "allowlist_gv11b.h"

static const u32 gv11b_hwpm_perfmon_register_offset_allowlist[] = {
	0x00000040,
	0x00000044,
	0x00000048,
	0x0000004c,
	0x00000050,
	0x00000054,
	0x00000058,
	0x0000005c,
	0x00000060,
	0x00000064,
	0x00000068,
	0x0000006c,
	0x00000070,
	0x00000074,
	0x00000078,
	0x0000007c,
	0x00000080,
	0x00000084,
	0x00000088,
	0x0000008c,
	0x00000090,
	0x00000094,
	0x00000098,
	0x0000009c,
	0x000000a0,
	0x000000a4,
	0x000000a8,
	0x000000ac,
	0x000000b0,
	0x000000b4,
	0x000000b8,
	0x000000bc,
	0x000000c0,
	0x000000c4,
	0x000000c8,
	0x000000cc,
	0x000000d0,
	0x000000d4,
	0x000000d8,
	0x000000dc,
	0x000000e0,
	0x000000ec,
	0x000000f8,
	0x000000fc,
	0x00000100,
	0x00000104,
	0x00000108,
	0x0000010c,
	0x00000110,
	0x00000120,
	0x00000124,
};

static const u32 gv11b_hwpm_router_register_offset_allowlist[] = {
	0x00000000,
	0x00000008,
	0x00000010,
	0x00000014,
};

static const u32 gv11b_hwpm_pma_channel_register_offset_allowlist[] = {
	0x00000080,
	0x00000084,
};

static const u32 gv11b_hwpm_pma_trigger_register_offset_allowlist[] = {
	0x00000000,
	0x00000008,
	0x00000010,
	0x00000014,
	0x00000018,
	0x0000001c,
	0x00000020,
	0x00000024,
	0x00000028,
	0x0000002c,
	0x00000030,
	0x00000034,
	0x00000038,
	0x00000040,
	0x00000044,
	0x00000048,
	0x00000050,
	0x00000054,
	0x00000058,
	0x00000060,
	0x00000064,
	0x00000068,
	0x0000006c,
	0x00000094,
	0x00000098,
	0x0000009c,
	0x000000a4,
	0x00000100,
	0x00000104,
	0x00000108,
	0x0000010c,
	0x00000110,
	0x00000114,
	0x00000600,
	0x00000604,
	0x00000608,
};

static const u32 gv11b_smpc_register_offset_allowlist[] = {
	0x00000200,
	0x00000204,
	0x00000208,
	0x0000020c,
	0x00000210,
	0x00000214,
	0x00000218,
	0x0000021c,
	0x00000220,
	0x00000224,
	0x00000228,
	0x0000022c,
	0x00000230,
	0x00000234,
	0x00000238,
	0x0000023c,
	0x00000240,
	0x00000244,
	0x00000248,
	0x00000300,
	0x00000304,
	0x00000308,
	0x0000030c,
	0x00000310,
	0x00000314,
	0x00000318,
	0x0000031c,
	0x00000320,
	0x00000324,
	0x00000328,
	0x0000032c,
	0x00000330,
	0x00000334,
	0x00000338,
	0x0000033c,
	0x00000340,
	0x00000344,
	0x00000348,
	0x0000034c,
	0x00000350,
	0x00000354,
	0x00000358,
	0x0000035c,
	0x00000360,
	0x00000364,
	0x00000368,
	0x0000036c,
	0x00000370,
	0x00000374,
	0x00000378,
	0x0000037c,
	0x00000380,
	0x00000384,
	0x00000388,
	0x0000038c,
	0x00000390,
	0x00000394,
	0x00000398,
	0x0000039c,
	0x000003a0,
	0x000003a4,
	0x000003a8,
	0x000003ac,
	0x000003b0,
	0x000003b4,
	0x000003b8,
	0x000003bc,
	0x000003c0,
	0x000003c4,
	0x00000600,
	0x00000604,
	0x00000608,
	0x0000060c,
	0x00000610,
	0x00000614,
	0x00000618,
	0x0000061c,
	0x00000620,
	0x00000624,
	0x00000628,
	0x0000062c,
	0x00000630,
	0x00000634,
	0x00000638,
	0x0000063c,
	0x00000640,
	0x00000644,
	0x00000648,
	0x0000064c,
	0x00000650,
	0x00000654,
	0x00000658,
	0x0000065c,
	0x00000660,
	0x00000664,
	0x00000668,
	0x0000066c,
	0x00000670,
	0x00000674,
	0x00000678,
	0x0000067c,
	0x00000680,
	0x00000684,
	0x00000688,
	0x0000068c,
	0x00000690,
	0x00000694,
	0x00000698,
	0x0000069c,
	0x000006a0,
	0x000006a4,
	0x000006a8,
	0x000006ac,
	0x000006b0,
	0x000006b4,
	0x000006b8,
	0x000006bc,
	0x000006c0,
	0x000006c4,
	0x00000700,
	0x00000704,
	0x00000708,
	0x0000070c,
	0x00000710,
	0x00000714,
	0x00000718,
	0x0000071c,
	0x00000720,
	0x00000724,
	0x00000728,
	0x0000072c,
	0x00000730,
	0x00000734,
	0x00000738,
	0x0000073c,
	0x00000740,
	0x00000744,
	0x00000748,
	0x0000074c,
	0x00000750,
	0x00000754,
	0x00000758,
	0x0000075c,
	0x00000760,
	0x00000764,
	0x00000768,
	0x0000076c,
	0x00000770,
	0x00000774,
	0x00000778,
	0x0000077c,
	0x00000780,
	0x00000784,
	0x00000788,
	0x0000078c,
	0x00000790,
	0x00000794,
	0x00000798,
	0x0000079c,
	0x000007a0,
	0x000007a4,
	0x000007a8,
	0x000007ac,
	0x000007b0,
	0x000007b4,
	0x000007b8,
	0x000007bc,
	0x000007c0,
	0x000007c4,
};

static const struct nvgpu_pm_resource_register_range gv11b_hwpm_perfmon_register_ranges[] = {
	{0x00180000, 0x00183ffc},
	{0x00250040, 0x00250124},
	{0x00250240, 0x00250324},
	{0x00278040, 0x0027bf24},
	{0x00200000, 0x00203ffc},
	{0x00250840, 0x00250924},
	{0x00250a40, 0x00250b24},
	{0x0027c040, 0x0027ff24},
	{0x00240000, 0x00243ffc},
};

static const struct nvgpu_pm_resource_register_range gv11b_hwpm_router_register_ranges[] = {
	{0x00244000, 0x002441fc},
	{0x00246000, 0x002461fc},
	{0x00248000, 0x002481fc},
	{0x00251800, 0x00251814},
	{0x00251a00, 0x00251a14},
};

static const struct nvgpu_pm_resource_register_range gv11b_hwpm_pma_channel_register_ranges[] = {
	{0x0024a070, 0x0024a08c},
};

static const struct nvgpu_pm_resource_register_range gv11b_hwpm_pma_trigger_register_ranges[] = {
	{0x0024a000, 0x0024a06c},
	{0x0024a090, 0x0024bffb},
};

static const struct nvgpu_pm_resource_register_range gv11b_smpc_register_ranges[] = {
	{0x00580000, 0x00587ffc},
	{0x00480000, 0x00487ffc},
};

static const struct nvgpu_pm_resource_register_range gv11b_hwpm_perfmux_register_ranges[] = {
	{0x000004f0, 0x000004f0},
	{0x00001a00, 0x00001a00},
	{0x000884e0, 0x000884e0},
	{0x00100c18, 0x00100c20},
	{0x00100c84, 0x00100c84},
	{0x0010a0a8, 0x0010a0a8},
	{0x0010a4f0, 0x0010a4f0},
	{0x0013c808, 0x0013c80c},
	{0x0013cc14, 0x0013cc14},
	{0x0013ec18, 0x0013ec18},
	{0x00140028, 0x00140028},
	{0x00140350, 0x00140350},
	{0x00140550, 0x00140550},
	{0x00140750, 0x00140750},
	{0x00142028, 0x00142028},
	{0x00142350, 0x00142350},
	{0x00142550, 0x00142550},
	{0x00142750, 0x00142750},
	{0x0017e028, 0x0017e028},
	{0x0017e350, 0x0017e350},
	{0x0017e550, 0x0017e550},
	{0x0017e750, 0x0017e750},
	{0x001fb000, 0x001fb000},
	{0x001fb400, 0x001fb400},
	{0x0040415c, 0x0040415c},
	{0x00405840, 0x00405844},
	{0x00405850, 0x00405850},
	{0x00405908, 0x00405908},
	{0x00405a00, 0x00405a00},
	{0x00405b50, 0x00405b50},
	{0x00406024, 0x00406024},
	{0x00407010, 0x00407010},
	{0x00407808, 0x00407808},
	{0x0040803c, 0x0040803c},
	{0x0040880c, 0x0040880c},
	{0x00408910, 0x00408910},
	{0x00408984, 0x00408984},
	{0x004090a8, 0x004090a8},
	{0x004098a0, 0x004098a0},
	{0x0041000c, 0x0041000c},
	{0x00410110, 0x00410110},
	{0x00410184, 0x00410184},
	{0x0041040c, 0x0041040c},
	{0x00410510, 0x00410510},
	{0x00410584, 0x00410584},
	{0x00418384, 0x00418384},
	{0x004184a0, 0x004184a0},
	{0x00418604, 0x00418604},
	{0x00418680, 0x00418680},
	{0x00418714, 0x00418714},
	{0x0041881c, 0x0041881c},
	{0x00418884, 0x00418884},
	{0x004188b0, 0x004188b0},
	{0x004188c8, 0x004188cc},
	{0x00418b04, 0x00418b04},
	{0x00418c04, 0x00418c04},
	{0x00418c10, 0x00418c2c},
	{0x00418c88, 0x00418c88},
	{0x00418d00, 0x00418d00},
	{0x00418e08, 0x00418e08},
	{0x00418f08, 0x00418f08},
	{0x0041900c, 0x0041900c},
	{0x00419018, 0x00419018},
	{0x00419854, 0x00419854},
	{0x00419ab0, 0x00419ab0},
	{0x00419b04, 0x00419b04},
	{0x00419bdc, 0x00419bdc},
	{0x00419c0c, 0x00419c0c},
	{0x0041a02c, 0x0041a030},
	{0x0041a0a8, 0x0041a0a8},
	{0x0041a8a0, 0x0041a8a8},
	{0x0041b014, 0x0041b014},
	{0x0041b0cc, 0x0041b0cc},
	{0x0041b1dc, 0x0041b1dc},
	{0x0041b214, 0x0041b214},
	{0x0041b2cc, 0x0041b2cc},
	{0x0041b3dc, 0x0041b3dc},
	{0x0041be14, 0x0041be14},
	{0x0041becc, 0x0041becc},
	{0x0041bfdc, 0x0041bfdc},
	{0x0041c054, 0x0041c054},
	{0x0041c2b0, 0x0041c2b0},
	{0x0041c304, 0x0041c304},
	{0x0041c3dc, 0x0041c3dc},
	{0x0041c40c, 0x0041c40c},
	{0x0041c854, 0x0041c854},
	{0x0041cab0, 0x0041cab0},
	{0x0041cb04, 0x0041cb04},
	{0x0041cbdc, 0x0041cbdc},
	{0x0041cc0c, 0x0041cc0c},
	{0x0041d054, 0x0041d054},
	{0x0041d2b0, 0x0041d2b0},
	{0x0041d304, 0x0041d304},
	{0x0041d3dc, 0x0041d3dc},
	{0x0041d40c, 0x0041d40c},
	{0x0041d854, 0x0041d854},
	{0x0041dab0, 0x0041dab0},
	{0x0041db04, 0x0041db04},
	{0x0041dbdc, 0x0041dbdc},
	{0x0041dc0c, 0x0041dc0c},
	{0x00500384, 0x00500384},
	{0x005004a0, 0x005004a0},
	{0x00500604, 0x00500604},
	{0x00500680, 0x00500680},
	{0x00500714, 0x00500714},
	{0x0050081c, 0x0050081c},
	{0x00500884, 0x00500884},
	{0x005008b0, 0x005008b0},
	{0x005008c8, 0x005008cc},
	{0x00500b04, 0x00500b04},
	{0x00500c04, 0x00500c04},
	{0x00500c10, 0x00500c2c},
	{0x00500c88, 0x00500c88},
	{0x00500d00, 0x00500d00},
	{0x00500e08, 0x00500e08},
	{0x00500f08, 0x00500f08},
	{0x0050100c, 0x0050100c},
	{0x00501018, 0x00501018},
	{0x00501854, 0x00501854},
	{0x00501ab0, 0x00501ab0},
	{0x00501b04, 0x00501b04},
	{0x00501bdc, 0x00501bdc},
	{0x00501c0c, 0x00501c0c},
	{0x0050202c, 0x00502030},
	{0x005020a8, 0x005020a8},
	{0x005028a0, 0x005028a8},
	{0x00503014, 0x00503014},
	{0x005030cc, 0x005030cc},
	{0x005031dc, 0x005031dc},
	{0x00503214, 0x00503214},
	{0x005032cc, 0x005032cc},
	{0x005033dc, 0x005033dc},
	{0x00503e14, 0x00503e14},
	{0x00503ecc, 0x00503ecc},
	{0x00503fdc, 0x00503fdc},
	{0x00504054, 0x00504054},
	{0x005042b0, 0x005042b0},
	{0x00504304, 0x00504304},
	{0x005043dc, 0x005043dc},
	{0x0050440c, 0x0050440c},
	{0x00504854, 0x00504854},
	{0x00504ab0, 0x00504ab0},
	{0x00504b04, 0x00504b04},
	{0x00504bdc, 0x00504bdc},
	{0x00504c0c, 0x00504c0c},
	{0x00505054, 0x00505054},
	{0x005052b0, 0x005052b0},
	{0x00505304, 0x00505304},
	{0x005053dc, 0x005053dc},
	{0x0050540c, 0x0050540c},
	{0x00505854, 0x00505854},
	{0x00505ab0, 0x00505ab0},
	{0x00505b04, 0x00505b04},
	{0x00505bdc, 0x00505bdc},
	{0x00505c0c, 0x00505c0c},
	{0x00900100, 0x00900100},
};

static const struct nvgpu_pm_resource_register_range gv11b_hwpm_pc_sampler_register_ranges[] = {
	{0x005043dc, 0x005043dc},
	{0x00504bdc, 0x00504bdc},
	{0x005053dc, 0x005053dc},
	{0x00505bdc, 0x00505bdc},
	{0x00419bdc, 0x00419bdc},
};

u32 gv11b_get_hwpm_perfmon_register_stride(void)
{
	return 0x00000200;
}

u32 gv11b_get_hwpm_router_register_stride(void)
{
	return 0x00000200;
}

u32 gv11b_get_hwpm_pma_channel_register_stride(void)
{
	return 0x00002000;
}

u32 gv11b_get_hwpm_pma_trigger_register_stride(void)
{
	return 0x00002000;
}

u32 gv11b_get_smpc_register_stride(void)
{
	return 0x00000800;
}

const u32 *gv11b_get_hwpm_perfmon_register_offset_allowlist(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_perfmon_register_offset_allowlist) /
		sizeof(gv11b_hwpm_perfmon_register_offset_allowlist[0]));
	return gv11b_hwpm_perfmon_register_offset_allowlist;
}

const u32 *gv11b_get_hwpm_router_register_offset_allowlist(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_router_register_offset_allowlist) /
		sizeof(gv11b_hwpm_router_register_offset_allowlist[0]));
	return gv11b_hwpm_router_register_offset_allowlist;
}

const u32 *gv11b_get_hwpm_pma_channel_register_offset_allowlist(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_pma_channel_register_offset_allowlist) /
		sizeof(gv11b_hwpm_pma_channel_register_offset_allowlist[0]));
	return gv11b_hwpm_pma_channel_register_offset_allowlist;
}

const u32 *gv11b_get_hwpm_pma_trigger_register_offset_allowlist(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_pma_trigger_register_offset_allowlist) /
		sizeof(gv11b_hwpm_pma_trigger_register_offset_allowlist[0]));
	return gv11b_hwpm_pma_trigger_register_offset_allowlist;
}

const u32 *gv11b_get_smpc_register_offset_allowlist(u32 *count)
{
	*count = (u32)(sizeof(gv11b_smpc_register_offset_allowlist) /
		sizeof(gv11b_smpc_register_offset_allowlist[0]));
	return gv11b_smpc_register_offset_allowlist;
}

const struct nvgpu_pm_resource_register_range
		*gv11b_get_hwpm_perfmon_register_ranges(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_perfmon_register_ranges) /
		sizeof(gv11b_hwpm_perfmon_register_ranges[0]));
	return gv11b_hwpm_perfmon_register_ranges;
}

const struct nvgpu_pm_resource_register_range
		*gv11b_get_hwpm_router_register_ranges(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_router_register_ranges) /
		sizeof(gv11b_hwpm_router_register_ranges[0]));
	return gv11b_hwpm_router_register_ranges;
}

const struct nvgpu_pm_resource_register_range
		*gv11b_get_hwpm_pma_channel_register_ranges(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_pma_channel_register_ranges) /
		sizeof(gv11b_hwpm_pma_channel_register_ranges[0]));
	return gv11b_hwpm_pma_channel_register_ranges;
}

const struct nvgpu_pm_resource_register_range
		*gv11b_get_hwpm_pma_trigger_register_ranges(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_pma_trigger_register_ranges) /
		sizeof(gv11b_hwpm_pma_trigger_register_ranges[0]));
	return gv11b_hwpm_pma_trigger_register_ranges;
}

const struct nvgpu_pm_resource_register_range
		*gv11b_get_smpc_register_ranges(u32 *count)
{
	*count = (u32)(sizeof(gv11b_smpc_register_ranges) /
		sizeof(gv11b_smpc_register_ranges[0]));
	return gv11b_smpc_register_ranges;
}

const struct nvgpu_pm_resource_register_range
		*gv11b_get_hwpm_perfmux_register_ranges(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_perfmux_register_ranges) /
		sizeof(gv11b_hwpm_perfmux_register_ranges[0]));
	return gv11b_hwpm_perfmux_register_ranges;
}

const struct nvgpu_pm_resource_register_range
		*gv11b_get_hwpm_pc_sampler_register_ranges(u32 *count)
{
	*count = (u32)(sizeof(gv11b_hwpm_pc_sampler_register_ranges) /
		sizeof(gv11b_hwpm_pc_sampler_register_ranges[0]));
	return gv11b_hwpm_pc_sampler_register_ranges;
}

