obj-$(CONFIG_BCMDHD_SDIO) += bcmdhd/
obj-$(CONFIG_BCMDHD_PCIE) += bcmdhd_pcie/
obj-$(CONFIG_RTL8812AU) += realtek/rtl8812au/
obj-$(CONFIG_RTL8814AU) += realtek/rtl8814au/
obj-$(CONFIG_RTL8821AU) += realtek/rtl8821au/
obj-$(CONFIG_RTL8822CE) += realtek/rtl8822ce/
