GCOV_PROFILE := y

obj-$(CONFIG_VIDEO_CDI)	+= cdi_gpio.o
obj-$(CONFIG_VIDEO_CDI)	+= cdi_mgr.o
obj-$(CONFIG_VIDEO_CDI)	+= cdi_dev.o
obj-$(CONFIG_VIDEO_CDI)	+= cdi_pwm.o
obj-$(CONFIG_VIDEO_CDI) += cdi_tsc.o
