ccflags-y += -I$(srctree)/drivers/devfreq
obj-$(CONFIG_DEVFREQ_GOV_POD_SCALING)   += governor_pod_scaling.o
obj-$(CONFIG_DEVFREQ_GOV_POD_SCALING_V2)   += governor_pod_scaling_v2.o
obj-$(CONFIG_DEVFREQ_GOV_WMARK_SIMPLE)  += governor_wmark_simple.o
obj-$(CONFIG_DEVFREQ_GOV_WMARK_ACTIVE)  += governor_wmark_active.o
