obj-$(CONFIG_TEGRA_KFUSE)			+= kfuse.o
tegra_fuse-objs					:= tegra-chipid.o
obj-$(CONFIG_TEGRA_FUSE_DOWNSTREAM)		+= tegra_fuse.o
obj-$(CONFIG_TEGRA_FUSE_DOWNSTREAM)		+= tegra-platform.o
obj-$(CONFIG_TEGRA_FUSE_BURN)			+= fuse-burn.o
