ccflags-y += -I$(srctree)/drivers/clk/tegra

obj-$(CONFIG_NV_TEGRA_BPMP)	+= clk-nv-bpmp.o
obj-$(CONFIG_NV_TEGRA_BPMP)	+= clk-tegra-bpmp.o
obj-$(CONFIG_NV_TEGRA_BPMP)	+= clk-fake.o
obj-$(CONFIG_TEGRA_AON)		+= tegra-aon-clk.o
obj-y				+= clk-skipper.o
obj-y				+= clk-cbus-shared.o
obj-y				+= clk-tegra-shared.o
obj-$(CONFIG_ARCH_TEGRA_210_SOC)	+= clk-tegra210b01.o
