obj-$(CONFIG_TEGRA_COMBINED_UART) += tegra-combined-uart.o
obj-$(CONFIG_TEGRA_COMBINED_UART_EARLY) += tegra-combined-uart-early.o
obj-$(CONFIG_TEGRA_HV_COMM)	+= tegra_hv_comm.o
obj-$(CONFIG_SERIAL_TEGRA_NOHW) += serial-tegra-nohw.o
obj-$(CONFIG_PCI_SERIAL_CH384) += wch_35x/
